### PR TITLE
Fix high vulnerability issues

### PR DESCRIPTION
**Pull request by sebastianks**
Fixes high vulnerability issues by updating axios and microbundle to their latest versions. This will help people that have `npm audit` to throw errors if the security level is `high`.

### CODE REVIEW

**Comment by sebastianks** [comment]
I am not sure how to fix the 1 failing travis check to be honest. The size snapshot is not failing locally for me 🤔

**Comment by sebastianks** [comment]
@developit Is this something you fancy taking a look at?

**Review by developit — APPROVED** [review]

**Comment by developit** [comment]
(FWIW, npm's definition of "high severity" here is woefully inaccurate - none of these dependencies are used in a way that would have any plausible security issue due to a regexp DOS / prototype pollution / etc)

**Comment by sebastianks** [comment]
@developit I get that, but some are restricted to <=Medium severity issues, which this would break. 

Thanks for merging 👍🏻

**Pull request merged**
